<?php
/**
 * Created by PhpStorm.
 * User: herald
 * Date: 31-Jul-17
 * Time: 15:17
 */

namespace App\Presenters;

use App\Logic\UserLogic;
use App\Model as Model;
use Kdyby\Doctrine\EntityManager;
use Nette;
use Tracy\Debugger;
use WebChemistry\Images\TPresenter;
use Kdyby\Monolog\Logger;

class BasePresenter extends Nette\Application\UI\Presenter{
	use \WebChemistry\Images\TPresenter;

	/** @var Logger @inject */
	public $logger;

	/**
	 * @var EntityManager @inject
	 */
	public $em;

	/**
	 * @var Model\CityFacade @inject
	 */
	public $cityFacade;

	/**
	 * @var Model\UniversityFacade @inject
	 */
	public $uniFacade;

	/**
	 * @var Model\CategoryFacade @inject
	 */
	public $categoryFacade;

	/**
	 * @var Model\PointFacade @inject
	 */
	public $pointFacade;

	/**
	 * @var Model\ImageFacade @inject
	 */
	public $imgFacade;

	/**
	 * @var Model\ContentFacade @inject
	 */
	public $contentFacade;

	/**
	 * @var Model\SubcFacade @inject
	 */
	public $subcFacade;
	
	/**
	 * @var Model\UserFacade @inject
	 */
	public $userFacade;
	
	public $base_path;

	public function startup(){
		$this->base_path = $this->getHttpRequest()->getUrl()->getBaseUrl();
		$this->template->base_path = $this->base_path;
		//Debugger::dump($this->getHttpRequest()->getUrl()->getBaseUrl());
		//Debugger::dump($this->getHttpRequest()->getUrl()->getBasePath());
		parent::startup(); // TODO: Change the autogenerated stub
	}
}