<?php
/**
 * Created by PhpStorm.
 * User: herald
 * Date: 24-Aug-17
 * Time: 14:09
 */

namespace App\FrontModule\Presenters;

use App\Presenters\BasePresenter;
use Nette;
use Nette\Application\UI\Form;

class LandingPresenter extends BasePresenter{

	public function startup(){
		parent::startup(); // TODO: Change the autogenerated stub
	}

	public function beforeRender(){
		if($this->getUser()->isLoggedIn()){
			$this->redirect(':Admin:Dashboard:');
		}
		parent::beforeRender();
	}


	public function actionOut(){
		$this->getUser()->logout();
		$this->flashMessage('Odhlášení bylo úspěšné.');
		$this->redirect(':Front:Landing:default');
	}


	protected function createComponentSignInForm(){
		$form = new Form();
		$form->addText('user_name','User name: ');
		$form->addText('psswd','Password:')->setRequired('Prosím vyplňte své heslo.');
		$form->addSubmit('signIn','Sign in');
		$form->onSuccess[] = [$this,'signInFormSucceeded'];
		return $form;
	}

	/**
	 * @param $form Nette\Application\UI\Form
	 * @param $values Nette\Utils\ArrayHash
	 */
	public function signInFormSucceeded($form, $values){
		try{
			$this->getUser()->login($values->user_name,$values->psswd);
			$this->logger->addInfo('[USER] Signed in (login)', ['user name' => $values->user_name]);
			$this->redirect(':Admin:Dashboard:');
		}catch(Nette\Security\AuthenticationException $e){
			$this->flashMessage('Nesprávné přihlašovací jméno nebo heslo.','danger');
			$this->logger->addInfo('[USER] Sign in failed (login)', ['user name' => $values->user_name]);
		}
	}

}